  name: AuthomaticUploader

  # This example workflow is meant to depict steps needed get the model-output data
  # from a data repository and open a pull request to upload data to a forked hub-repository
  # A good starting point for a better understandig of how GitHub actions work
  # is this: https://docs.github.com/en/actions/quickstart

  # This workflow should be placed under the .github/workflows folder of you forked repo

  # Firts step is to define di events that can trigger this workflow
  on:

    # Run on schedule
    schedule:
    - cron: "30 15 * * 3"

    # Or you can manually trigger the workflow
    workflow_dispatch:

  jobs:
    create_PR_job:
      runs-on: ubuntu-latest


      steps:

        # Checkout your forked repository - main branch -
        # where this action is currently hosted
        # ---------------------------------------------------
        - name: checkout forked repository
          uses: actions/checkout@v3
          with:
            ref: main
            token: ${{ secrets.GITHUB_TOKEN }}

        # Checkout the model data repository - main branch -
        # This is the repository where previous wf saved the model output data
        # In this example data repo is https://github.com/your_organization/data-repo
        # -----------------------------------------------------------------------------
        - name: checkout data repository
          uses: actions/checkout@v3
          with:
            ref: 'main' # the git branch to work on
            token: ${{ secrets.GITHUB_TOKEN }}
            repository: 'Chappi74/web-test/'
            path: './data-repo/' # Relative path under $GITHUB_WORKSPACE to place the repository



        # Set the default remote repository to use when querying the GitHub API for the locally cloned repository.
        - run: gh repo set-default Testing-Forecast-Actions/RespiCast-SyndromicIndicators
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


        # Sync forked repo main branch, pull and then switch to a new brench
        - run: |
            git config --global user.email "paolo.milano@gmail.com"
            git config --global user.name "Chappi74"
            gh repo sync Chappi74/Fork-Test-RespiCast-SyndromicIndicators -b main
            git pull
            git checkout -b pr-new-branch

          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # make a copy of the needed files from source repo to local fork
        - name: Copy model-output file
          run: cp ./data-repo/archive/2024-12-04-ISI-TestModel.csv ./model-output/ISI-TestModel

        # commit change to a new brach! This step is needed in order
        # to succesfully open the subsequent pull request
        - run: |
            git add ./model-output/ISI-TestModel/2024-12-04-ISI-TestModel.csv
            git commit -m "AuthoSubmitPR"
            git push -u origin pr-new-branch


        # Finally, open the pull request from local pr-new-branch to the main branch
        # secrets.MY_PAT_SECRET is a repository secret you have to create in your forked repository
        # containing a valid PERSONAL ACCESS TOKEN for YourGitHubUserName.
        # Without this secret the pr create fails with "Resource not accessible by integration" error
        - name: Open the pull requests
          run: gh pr create --head  Chappi74:pr-new-branch  --base main --title 'PR Title' --body 'PR Body'
          env:
            GH_TOKEN: ${{ secrets.MY_PAT_SECRET  }}
